consul:
    image: qnib/alpn-consul
    hostname: consul
    container_name: ${USER}_consul
    dns: 127.0.0.1
    ports:
     - 8500
    environment:
     - DC_NAME=dc1
     - CONSUL_BOOTSTRAP=true

registry:
    hostname: registry
    container_name: ${USER}_registry
    image: qnib/registry
    dns: 127.0.0.1
    ports:
     - 80
    environment:
     - DC_NAME=dc1
    links:
     - consul:consul
